# Generated by Django 5.0.2 on 2026-01-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandates', '0003_mandate_is_near_expiry_notified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandate',
            name='broker_selfie',
            field=models.ImageField(blank=True, null=True, upload_to='selfies/brokers/'),
        ),
        migrations.AddField(
            model_name='mandate',
            name='seller_selfie',
            field=models.ImageField(blank=True, null=True, upload_to='selfies/sellers/'),
        ),
    ]
