# Generated by Django 5.0.2 on 2026-01-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandates', '0004_mandate_broker_selfie_mandate_seller_selfie'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandate',
            name='mandate_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
