# Generated by Django 5.0.2 on 2026-01-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role_category',
            field=models.CharField(choices=[('BUYER', 'Buyer'), ('SELLER', 'Seller'), ('BUILDER', 'Builder'), ('BROKER', 'Real Estate Agent'), ('PLOTTING_AGENCY', 'Plotting Company/Agency')], default='BUYER', max_length=20),
        ),
    ]
