# Generated by Django 5.0.2 on 2026-01-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_role_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_kyc_verified',
            field=models.BooleanField(default=False),
        ),
    ]
