# Generated by Django 5.0.2 on 2026-01-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_kyc_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycverification',
            name='verified_by',
            field=models.CharField(blank=True, choices=[('DIGILOCKER', 'DigiLocker'), ('ADMIN', 'Admin Manual Verification')], max_length=20, null=True),
        ),
    ]
