# Generated by Django 5.0.2 on 2025-12-31 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kycverification',
            name='digilocker_json',
        ),
        migrations.RemoveField(
            model_name='kycverification',
            name='pan_number',
        ),
        migrations.AddField(
            model_name='kycverification',
            name='address_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='sandbox_request_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('INITIATED', 'Initiated'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed')], default='NOT_STARTED', max_length=20),
        ),
    ]
